gpt-3.5-turbo-0613:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-3.5-turbo-0613"
        body:
            model: "gpt-3.5-turbo-0613"
            max_tokens: 512

text-davinci-003:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-003"
        body:
            model: "text-davinci-003"
            max_tokens: 512

text-davinci-002:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-002"
        body:
            model: "text-davinci-002"
            max_tokens: 512

gpt-3.5-turbo:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-3.5-turbo"
        body:
            model: "gpt-3.5-turbo"
            max_tokens: 512

gpt-3.5-turbo-1106:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-3.5-turbo-1106"
        body:
            model: "gpt-3.5-turbo-1106"
            max_tokens: 512

gpt-4o-2024-05-13:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-4o-2024-05-13"
        body:
            model: "gpt-4o-2024-05-13"
            max_tokens: 512

gpt-4-turbo:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-4-turbo"
        body:
            model: "gpt-4-turbo"
            max_tokens: 512

gpt-4:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-4"
        body:
            model: "gpt-4"
            max_tokens: 512

mistral-7b-instruct:
    import: "./lmstudio_agent.yaml"
    parameters:
        name: "mistral-7b-instruct"
        body:
            model: "TheBloke/Mistral-7B-Instruct-v0.1-GGUF"
            max_tokens: 512

Llama-3-8B-Instruct:
    import: "./lmstudio_agent.yaml"
    parameters:
        name: "Llama-3-8B-Instruct"
        body:
            model: "lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF"
            max_tokens: 512
